const products = [
    {
      _id: '1',
      name: 'Airpods Wireless Bluetooth',
      image: '/images/airpods.jpg',
      description: 'Bluetooth technology lets you connect it with compatible devices wirelessly. High-quality AAC audio offers an immersive listening experience. Built-in microphone allows you to take calls while working.',
      brand: 'Apple',
      category: 'Electronics',
      price: 89.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Smartphone X Pro',
      image: '/images/phone.jpg',
      description: 'Powerful smartphone with advanced features. High-resolution camera, long-lasting battery, and sleek design.',
      brand: 'TechCo',
      category: 'Electronics',
      price: 699.99,
      countInStock: 5,
      rating: 4.8,
      numReviews: 8,
    },
    {
      _id: '3',
      name: 'UltraHD 4K Smart ',
      image: '/images/camera.jpg',
      description: 'Experience stunning visuals with this UltraHD 4K Smart TV. Stream your favorite shows and movies with ease.',
      brand: 'VisionTech',
      category: 'Electronics',
      price: 1299.99,
      countInStock: 3,
      rating: 4.7,
      numReviews: 15,
    },
    {
      _id: '4',
      name: 'Wireless Gaming ',
      image: '/images/mouse.jpg',
      description: 'Enhance your gaming experience with this wireless gaming mouse. Precise tracking and customizable buttons.',
      brand: 'GamerGear',
      category: 'Gaming',
      price: 49.99,
      countInStock: 8,
      rating: 4.2,
      numReviews: 6,
    },
    {
      _id: '5',
      name: 'Fitness Tracker Watch',
      image: '/images/sample.jpg',
      description: 'Monitor your health and fitness goals with this advanced fitness tracker watch. Heart rate monitoring and activity tracking.',
      brand: 'FitLife',
      category: 'Fitness',
      price: 79.99,
      countInStock: 12,
      rating: 4.6,
      numReviews: 10,
    },
    {
      _id: '6',
      name: 'Wireless Bluetooth',
      image: '/images/alexa.jpg',
      description: 'Enjoy music on the go with these comfortable wireless Bluetooth earbuds. Clear sound and long battery life.',
      brand: 'SoundWave',
      category: 'Electronics',
      price: 39.99,
      countInStock: 15,
      rating: 4.3,
      numReviews: 9,
    },
    {
      _id: '7',
      name: 'Gaming Console -',
      image: '/images/playstation.jpg',
      description: 'Immerse yourself in the world of gaming with the PlayStation X. Stunning graphics and a vast library of games.',
      brand: 'Sony',
      category: 'Gaming',
      price: 499.99,
      countInStock: 4,
      rating: 3.9,
      numReviews: 7,
    },
  ];
  
  export default products
